Add kops Lab
cloud-native-taiwan/Infra-Labs-Docs pull request #12
Opened 2022-05-26 02:14 UTC by ching-kuo

This commit add kops lab. In the kops lab, we walk through the
introduction of kops and how to create a Kubernetes cluster on OpenStack
with kops.

2022-05-26 02:35 UTC, kkdai approved these changes
LGTM 
如果可以改成 mermaid 來做說明圖，就不用另外輸出檔案。
避免不是每個人都有 drawio 的軟體權限

2022-05-26 02:35 UTC, kkdai commented on self-paced-labs/k8s/kops/README.md
> +![architecture](img/architecture.png)
要不要改成原生支持的 mermaid 不用另外輸出 PNG

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

2022-05-26 02:40 UTC, ching-kuo commented on self-paced-labs/k8s/kops/README.md
> +![architecture](img/architecture.png)
我看了一下目前好像還不太適合用來畫 architecture diagram
flow chart 跟 sequence diagram 就還蠻適合的

2022-05-26 02:44 UTC, kkdai commented on self-paced-labs/k8s/kops/README.md
> +![architecture](img/architecture.png)
或是可以檢查一下這個方式 

https://drawio.freshdesk.com/support/solutions/articles/16000042371-embed-a-diagram-in-github-markdown
https://github.com/jgraph/drawio-github

2022-06-08 04:42 UTC, steveyiyo requested changes

2022-06-08 04:42 UTC, steveyiyo commented on self-paced-labs/k8s/kops/README.md
> +- 支援 AWS (production)、OpenStack/Digital Ocean (Beta)、Azure/GCP (Alpha)
DigitalOcean 的名字是合在一起的 XD

2022-06-08 04:42 UTC, steveyiyo commented on self-paced-labs/k8s/kops/README.md
> +```
建議加上以下兩行，這樣在編譯完成後可以自動安裝。

```shell
chmod +x $(go env GOBIN)/kops
sudo mv $(go env GOBIN)/kops /usr/local/bin/kops
```

2022-06-08 04:42 UTC, steveyiyo commented on self-paced-labs/k8s/kops/README.md
> +### 下載 OpenStack Credential
官方文件建議使用  Application Credentials

> We recommend using Application Credentials when authenticating to OpenStack.
> 
> Note The authentication used locally will be exported to your cluster and used by the kubernetes controller components. You must avoid using personal credentials used for other systems,
> 
> Ref: https://kops.sigs.k8s.io/getting_started/openstack/#source-your-openstack-rc

2022-06-08 04:42 UTC, steveyiyo commented on self-paced-labs/k8s/kops/README.md
> +### 下載 OpenStack Credential
可以參考我在 [FRR BGP Lab 教學文件](https://github.com/cloud-native-taiwan/Infra-Labs-Docs/blob/b37af548eaf3e8655c208df4d43876fcb8e56891/self-paced-labs/network/frr_bgp/README.md#how-to-run-terraform-script) 中的寫法

2022-07-31 05:42 UTC, ching-kuo commented on self-paced-labs/k8s/kops/README.md
> +```
GOBIN 本來應該就要在 PATH 內吧

2022-08-02 07:55 UTC, ching-kuo commented on self-paced-labs/k8s/kops/README.md
> +### 下載 OpenStack Credential
fixed

2022-08-02 07:55 UTC, ching-kuo commented on self-paced-labs/k8s/kops/README.md
> +- 支援 AWS (production)、OpenStack/Digital Ocean (Beta)、Azure/GCP (Alpha)
fixed

2022-11-16 16:40 UTC, steveyiyo approved these changes

2022-12-13 14:03 UTC, merged