Add build tool compare lab
cloud-native-taiwan/Infra-Labs-Docs pull request #24
Opened 2022-12-22 10:02 UTC by kn71026

This PR adds a lab on building container images with various tools. In this lab, we introduce several tools for building container images and compare the computational resources used when using these tools.

2022-12-28 09:33 UTC, ydFu reviewed
圖表建議，
1. 按照 bulid tools 字母大小或是文章列舉方式進行統一的排序，不建議每個圖表排序方式不同
2. cpu、build time 只有使用 4 個 bulid tools ，memory、image size 只有使用 5 個 bulid tools
3. 直方圖建議列出實際測試數值
4. 在圖表中加入單位資訊

2022-12-28 09:33 UTC, ydFu commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- VCPUS：4
缺少單位

2022-12-28 09:33 UTC, ydFu commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +在這篇文章中，將會簡介目前常見的幾種 Image Building Tools，並比較這些工具在 build image 時花費的 Memory/ Build Time/ CPU time，以及不同工具最後 build 出的 Image Size 是否有所不同，以及探討其中的差異。
1. 建議本次 Lab 列出選擇 Image Building Tools 的原因
2. 比較的四項指標(CPU time,Memory,Build Time,Image Size)，可以調整描述方式，建議使用頓號(、)斷句，使用逗號(，)不太容易看出是一起比較的指標。

2022-12-28 09:33 UTC, ydFu commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- https://www.datadoghq.com/blog/how-to-collect-docker-metrics/
參考連結可以簡述。

2022-12-28 09:33 UTC, ydFu commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- 單位為MB
```suggestion
- 單位為 MB
```

2022-12-29 08:21 UTC, ching-kuo reviewed
如果可以的話在圖表上加上 Title 跟單位會比較好
然後有些在 bar 上面有原始數值，建議在其他沒有的也可以加上

然後最近因為改用網站的形式呈現，可能需要更改一下 PR 的架構

2022-12-30 02:06 UTC, ching-kuo reviewed
加上之前 Hwchiu 曾經傳給我的 comments

2022-12-30 02:06 UTC, ching-kuo commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +Buildkit 為 Docker 推出的實驗性功能，主打更高效能、並行的運作方式，也針對 cache,  storage management 等功能做了許多優化，加速了以往使用 docker build image 的流程以及最佳化使用體驗，預設內建在 `Docker 18.09` 版本之後的 docker 內，啟用方式也十分簡易，`DOCKER_BUILDKIT=1 docker buil
記得 MacOS/Linux 的預設設定不同

2022-12-30 02:06 UTC, ching-kuo commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +可參考 [Kaniko 教學](https://github.com/cloud-native-taiwan/Infra-Labs-Docs/tree/main/self-paced-labs/image_build/kaniko_lab)
建議可以補充簡短說明

2022-12-30 02:06 UTC, ching-kuo commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +使用 docker 運行 kaniko v1.8.1 的 container，並將 build 好的 image 推到 dockerhub 上
為什麼就你需要 push image

2022-12-30 02:06 UTC, ching-kuo commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +| Remote layer caching        | O| O | O | O   |
結尾出現
Remote layer caching 

結果文章都沒有提到這個功能？

有點不知這個功能的好壞與意義

2022-12-30 02:37 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- VCPUS：4
@ydFu 想請問一下，單位是指 core 嗎

2023-01-02 02:44 UTC, hwchiu commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- VCPUS：4
Yes, 另外可以不需要全部大寫 我看了有點久才懂是vCPU

2023-01-02 02:47 UTC, hwchiu reviewed
許願，希望之後可以針對這部分繼續擴充如是否支援多架構建置的功能，隨者M1 Mac 的出現，很多人都變成要用M1開發，為了測試可能還需要可以產生 amd64 架構的image

2023-01-09 07:48 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +使用 docker 運行 kaniko v1.8.1 的 container，並將 build 好的 image 推到 dockerhub 上
因為其他的 build tool build 完後的 image 會存在本地端，但使用 kaniko build 通常會需要指定 destination registry，如果用預設的 --no-push 雖然不會 push image，但就看不到 build 好的 image 跟 image size。

2023-01-09 07:48 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +可參考 [Kaniko 教學](https://github.com/cloud-native-taiwan/Infra-Labs-Docs/tree/main/self-paced-labs/image_build/kaniko_lab)
已補充

2023-01-09 07:49 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +Buildkit 為 Docker 推出的實驗性功能，主打更高效能、並行的運作方式，也針對 cache,  storage management 等功能做了許多優化，加速了以往使用 docker build image 的流程以及最佳化使用體驗，預設內建在 `Docker 18.09` 版本之後的 docker 內，啟用方式也十分簡易，`DOCKER_BUILDKIT=1 docker buil
ok 我補充一下其他啟用的方式

2023-01-09 07:51 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +在這篇文章中，將會簡介目前常見的幾種 Image Building Tools，並比較這些工具在 build image 時花費的 Memory/ Build Time/ CPU time，以及不同工具最後 build 出的 Image Size 是否有所不同，以及探討其中的差異。
已補充

2023-01-09 07:52 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- https://www.datadoghq.com/blog/how-to-collect-docker-metrics/
已補充

2023-01-09 07:52 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- 單位為MB
已修正

2023-01-09 07:52 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +- VCPUS：4
ok 已修改

2023-01-09 08:32 UTC, kn71026 commented on self-paced-labs/image_build/tool_compare_lab/README.md
> +| Remote layer caching        | O| O | O | O   |
因為這次測的 lab 都是 build php-fpm，比較沒有需要拿之前 build 好的 remote registry image 的情況，所以沒有特別提到，但在 CICD 過程中。如果使用多台 runner，應該就會需要這個功能去拿 cache 以減少過程花費時間。

2023-01-12 02:42 UTC, kn71026 commented
已修改 PR 架構為網站的形式以及根據 comment 修正/補充文章內容

2023-01-16 06:50 UTC, ching-kuo approved these changes
LGTM

2023-01-16 07:26 UTC, tico88612 requested changes
裡面有些專有名詞開頭需要大寫

像是這段

> 使用 docker 運行 kaniko v1.8.1 的 container，並將 build 好的 image 推到 dockerhub 上

更改

> 使用 Docker 運行 Kaniko v1.8.1 的 container，並將 build 好的 image 推到 DockerHub 上

2023-01-16 07:26 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +Buildkit 為 Docker 推出的實驗性功能，主打更高效能、並行的運作方式，也針對 cache, storage management 等功能做了許多優化，加速了以往使用 docker build image 的流程以及最佳化使用體驗，預設內建在 `Docker 18.09` 版本之後的 docker 內，啟用方式也十分簡易，`DOCKER_BUILDKIT=1 docker build
> `DOCKER_BUILDKIT=1 docker build .`即可使用

add space

> `DOCKER_BUILDKIT=1 docker build .` 即可使用

2023-01-16 07:26 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +`dokcerfile` 中的每條指令可視為一個 layer，在 build 的過程中會比較 Layer 與之前是否相同，若相同在使用 docker build 時會顯示 `Using cache` 以及使用了哪個 cache，cahce 則會存在 `/var/lib/docker/image/overlay2/imagedb/content/sha256` 底下，若是使用 BuildKit，則
> `dokcerfile` => `Dockerfile`

> docker build 時會顯示 => `docker build` 時會顯示

> 因此在撰寫 dockerfile 時可以將比較常更改的內容放在 `dokcerfile` 尾端。

fix

> 因此在撰寫 Dockerfile 時可以將比較常更改的內容放在 `Dockerfile` 尾端。

2023-01-16 08:39 UTC, ydFu reviewed
下列兩個圖表中皆缺少 Kaniko 測試資料，再麻煩了
docs/self-paced-labs/tool_compare_lab/image/memory.png
docs/self-paced-labs/tool_compare_lab/image/build_time.png

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +在這篇文章中，將會簡介目前常見的幾種 Image Building Tools，分別是目前最常見的 Docker 以及新版本內建的 Buildkit、以及常被用在 CICD 過程中的三套 Build tool：Dind(Docker in Docker), Buildah, Kaniko 作比較。
```suggestion
在這篇文章中，將會簡介目前常見的五種 Image Building Tools，分別是目前最常見的 Docker 以及新版本內建的 Buildkit、以及常被用在 CICD 過程中的三套 Build tool：Dind(Docker in Docker), Buildah, Kaniko 作比較。
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +並比較這些工具在 build image 時花費的系統資源：
```suggestion
比較這些上述五項  Image Building Tools 在 build image 時所花費的系統資源，如下述三項指標：
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- Memory
```suggestion
- Memory(有 cache/無 cache)
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +  以及不同工具最後 build 出的 Image Size 是否有所不同，以及探討其中的差異。
```suggestion
  並比較 build 完成後， Image Size 是否有所不同，並探討其中的差異。
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- Ubuntu 20.04
```suggestion
- Linux version: Ubuntu 20.04
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- 4 cores vCPU
```suggestion
-  vCPU: 4 cores
```

2023-01-16 08:39 UTC, ydFu commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- RAM：4G
```suggestion
- RAM：4 G
```

2023-02-01 03:23 UTC, kn71026 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +Buildkit 為 Docker 推出的實驗性功能，主打更高效能、並行的運作方式，也針對 cache, storage management 等功能做了許多優化，加速了以往使用 docker build image 的流程以及最佳化使用體驗，預設內建在 `Docker 18.09` 版本之後的 docker 內，啟用方式也十分簡易，`DOCKER_BUILDKIT=1 docker build
已修正

2023-02-01 03:23 UTC, kn71026 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +`dokcerfile` 中的每條指令可視為一個 layer，在 build 的過程中會比較 Layer 與之前是否相同，若相同在使用 docker build 時會顯示 `Using cache` 以及使用了哪個 cache，cahce 則會存在 `/var/lib/docker/image/overlay2/imagedb/content/sha256` 底下，若是使用 BuildKit，則
已修正

2023-02-01 03:25 UTC, kn71026 commented
> 下列兩個圖表中皆缺少 Kaniko 測試資料，再麻煩了 docs/self-paced-labs/tool_compare_lab/image/memory.png docs/self-paced-labs/tool_compare_lab/image/build_time.png

build time 的部分已補上，memeory 的部分因為測 kaniko 沒有用 local layer cache，因此在 memory 上圖應該是沒有數據的，原本放錯了，已修正並在文章內補上原因。

2023-02-02 13:32 UTC, tico88612 reviewed
這個是我目前看到還有一些小問題，改完我這裡就 Review 完成。

2023-02-02 13:32 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +ydFu2 週前
這行是不是多了？

2023-02-02 13:32 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> + 並比較 build 完成後，Image Size 是否有所不同，並探討其中的差異。
第一個字元是空格？

2023-02-02 14:17 UTC, kn71026 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +ydFu2 週前
是 不小心複製到了 已修改

2023-02-02 15:46 UTC, tico88612 reviewed
Local 跑檢查的時候有看到一些新問題

2023-02-02 15:46 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +並比較 build 完成後，Image Size 是否有所不同，並探討其中的差異。
Line 16 再多空一行，不然 Render 會變這樣
![image](https://user-images.githubusercontent.com/17496418/216369615-30b1d2df-6999-42e4-bb0d-9b0e6b49b34b.png)

2023-02-02 15:46 UTC, tico88612 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- 測試方法會在下方 Labs 區塊中詳述
```
...
- RAM：4 G
- total Disk：30 GB
- 測試方法會在下方 Labs 區塊中詳述
...
```

這樣應該會比較好讀一點

```
...
- RAM：4 G
- total Disk：30 GB

測試方法會在 [Labs](#labs) 區塊中詳述。
...
```

2023-02-20 05:09 UTC, kn71026 commented on docs/self-paced-labs/tool_compare_lab/index.md
> +- 測試方法會在下方 Labs 區塊中詳述
已修正

2023-02-20 06:13 UTC, tico88612 approved these changes
LGTM!

今晚 8 點前 (UTC+8) 如果沒有其他成員提出問題，就會執行 Merge。

2023-02-20 07:22 UTC, ydFu approved these changes
LGTM

2023-02-20 12:29 UTC, merged