feat: add helm charts
cloud-native-taiwan/Infra-Labs-Docs pull request #48
Opened 2023-09-11 14:26 UTC by CCH0124

Helm charts 整合 yaml 驗證、檔案掃描、文件整合以及 helm cli 使用

2023-09-12 00:04 UTC, steveyiyo approved these changes
LGTM, thanks for the contribution!

2023-09-12 00:42 UTC, tico88612 requested changes
Initial review

表格還沒看呈現方式，剛剛初步看覺得有點過長，之後會再 review。

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +透過本文章會學習到以下:
```suggestion
透過本文章會學習到以下：
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +此文章範例來源代碼可以至此[連結](https://github.com/CCH0124/quarkus-demo/tree/main/helm-demo)
```suggestion
此文章範例來源程式碼可以至此[連結](https://github.com/CCH0124/quarkus-demo/tree/main/helm-demo)
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +- OS: Windows 11 WSL(Ubuntu 22.04)
```suggestion
- OS: Windows 11 WSL (Ubuntu 22.04)
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +此時會建立一些基礎的資源，更詳細的 `charts` 結構內容可參閱其官方[資源](https://helm.sh/docs/topics/charts/)。
我在想這裡應該是要說官方文件？資源有點差異

```suggestion
此時會建立一些基礎的資源，更詳細的 `charts` 結構內容可參閱其官方[文件](https://helm.sh/docs/topics/charts/)。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +這邊使用 `include` 函式將其 `web-app.annotation` 模板引入，並使用 `.` 將其作為一個值，最後將結果往 `indent ` 函示傳入。Helm 提供多種的模板函數，有興趣者可以至此[官方文檔](https://helm.sh/docs/howto/charts_tips_and_tricks/)進行查看。
```suggestion
這邊使用 `include` 函式將其 `web-app.annotation` 模板引入，並使用 `.` 將其作為一個值，最後將結果往 `indent ` 函示傳入。Helm 提供多種的模板函數，有興趣者可以至此[官方文件](https://helm.sh/docs/howto/charts_tips_and_tricks/)進行查看。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +當模板定義好之後，必須將其填充資料，否則無法正常被 Kubernetes 執行。在預設上會使用 `values.yaml` 進行填充。
呼叫一下 @ydFu  
填充資料會是比較好的講法嗎？

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +
```suggestion
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +
```suggestion
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +本實驗是用 ubuntu 環境直接安裝，其它方式可參閱此[連結](https://github.com/yannh/kubeconform#installation)
```suggestion
本實驗是用 ubuntu 環境直接安裝，其它方式可參閱此[連結](https://github.com/yannh/kubeconform#installation)

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +驗證過程會建議，指定 Kubernetes 版本來進行驗證，Kubernetes 每個版本的 API 會有所不同，這樣可以明確知道 `charts` 可以在哪個環境運行。避免 Kubernetes 升級後帶來的災難。
```suggestion
驗證過程會建議，指定 Kubernetes 版本來進行驗證，Kubernetes 每個版本的 API 會有所不同，這樣可以明確知道 `charts` 可以在哪個環境運行。避免 Kubernetes 升級後帶來的災難。

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +Helm 透過這種設計做到了 Kubernetes 原生無法管理 `yaml` 的問題。到這邊可以了解模板如何渲染，但在渲染前可以對 `charts` 進行格式上驗證，驗證模板中的格式是否正確，但此階段無法確保渲染出來的 Kubernetes 資源可被使用。
@ydFu 渲染 (render) 有沒有更好的說法？

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +有興趣者可以藉由[官方](https://kube-score.com/)位置進行體驗。
```suggestion
有興趣者可以藉由[官方網站](https://kube-score.com/)進行體驗。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +## charts 整合 helm-docs 產生文件
```suggestion
## charts 整合 helm-docs 產生文件

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +
```suggestion
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果:
```suggestion
渲染結果：
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果:
```suggestion
渲染結果：
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果:
```suggestion
渲染結果：
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +- `@default` 如果不想包含在 values.yaml 中的默認值，或是一些計算的值可以使用
```suggestion
- `@default` 如果不想包含在 values.yaml 中的預設值，或是一些計算的值可以使用
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +### 打包 charts
```suggestion
## 打包 charts 至 DockerHub

### 打包 charts
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +### 登入 Docker Hub 並推送
```suggestion
### 登入 Docker Hub 並推送

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +### 佈署
```suggestion
### 佈署

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +在佈署之前，可以藉由 `helm show` 來進行一些資訊查看。
```suggestion
佈署之前，可以藉由 `helm show` 來進行一些資訊查看。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +```
```suggestion
1. 驗證佈署

對於 Helm 來說它是有 namespace 概念，因此在操作時須帶 `namespace`，從 `STATUS` 欄位可以看到是成功佈署的。

```bash
$ helm list 
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
web-app default         1               2023-09-11 20:57:10.735141112 +0800 CST deployed        web-app-0.0.1   1.16.0     
```
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +上個步驟在佈署時，沒有佈署到 `ingress`，這時使用 `helm upgrade` 進行。
```suggestion
### 更新 Helm chart

上個步驟在佈署時，沒有佈署到 `ingress`，這時使用 `helm upgrade` 進行。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +下面為一個錯誤的更新，導致最後 `STATUS` 為 `failed`。
```suggestion
下面為一個錯誤的更新，導致最後 `STATUS` 為 `failed`。

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +驗證結果，如下:
```suggestion
驗證結果，如下：

```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +到這邊認識了 Helm 的概念:
```suggestion
到這邊認識了 Helm 的概念：
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +另一方面，`charts` 可以被版控，也可以針對每個環境使用不同的 `values.yaml` 來做渲染，減少了管理多環境的資源，同時對於現今的 gitops 概念來說可以做一個很好的整合。
```suggestion
另一方面，`charts` 可以被版控，也可以針對每個環境使用不同的 `values.yaml` 來做渲染，減少了管理多環境的資源，同時對於現今的 GitOps 概念來說可以做一個很好的整合。
```

2023-09-12 00:42 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +最後補充 `.helmignore`，在打包時請考慮要不要將一些檔案給識別掉，避免敏感資訊被洩漏。
這段我覺得還可以再改善

```suggestion
最後補充 `.helmignore`，打包時請考慮把敏感資料忽略，避免機密外洩。
```

2023-09-12 02:15 UTC, CCH0124 commented on docs/self-paced-labs/helm-charts/index.md
> +透過本文章會學習到以下:
Hi, @tico88612 
這 `:` 部分都會建議是全形嗎 ?

2023-09-12 02:18 UTC, CCH0124 commented on docs/self-paced-labs/helm-charts/index.md
> +如果要將結果輸出至 `CI` 的產物可以使用 `-o FILE_NAME` 方式，輸出的檔案會取決於在哪個目錄執行 `helm unittest`。
@tico88612 `artifact` 說成**產物**會是一個好的說法嗎 ?

2023-09-12 05:58 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +透過本文章會學習到以下:
可以參考中文文案排版指北說明，中文會建議使用全形冒號

https://github.com/sparanoid/chinese-copywriting-guidelines

2023-09-12 06:47 UTC, ydFu commented on docs/self-paced-labs/helm-charts/index.md
> +如果要將結果輸出至 `CI` 的產物可以使用 `-o FILE_NAME` 方式，輸出的檔案會取決於在哪個目錄執行 `helm unittest`。
其實繁體中文在科技用語的使用習慣文化，本來就是中英混用，不用像簡體中文習慣一對一對應，你不確定的情況下也可以直接使用原文。

2023-09-12 09:07 UTC, CCH0124 commented on docs/self-paced-labs/helm-charts/index.md
> +如果要將結果輸出至 `CI` 的產物可以使用 `-o FILE_NAME` 方式，輸出的檔案會取決於在哪個目錄執行 `helm unittest`。
了解 👍

2023-09-12 12:29 UTC, CCH0124 commented
部分語句已做建議上調整 😆

2023-09-17 03:21 UTC, tico88612 requested changes
非常感謝前面修正，不過我這裡覺得還有幾個需要修改：

1. 翻譯修正

`回滾` => `退回` https://github.com/cncf/glossary/pull/2035#discussion_r1208790399  
`渲染` => `轉譯` https://breezymove.blogspot.com/2013/12/render.html

2. 文章連結命名

資料夾連結不要直接命名為 `helm-charts`（會以為只有 Helm Chart 教學），建議名稱為 `quarkus-with-helm-charts` 等其他命名。

3. 壓縮成同一個 commit 即可，感謝！

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +修正後，已經成功更新一個版本，`REVISION` 變為 3，`ingress` 資源也被更新佈署。在做更新時也推薦使用 `--atomic` 參數，這可幫助 `charts` 更新失敗後可以進行回滾。這邊使用的是 `--set` 方式同時也是可以使用 `-f` 來指定要渲染模板的值，以優先順序來說 `--set` 為最高。
```suggestion
修正後，已經成功更新一個版本，`REVISION` 變為 3，`ingress` 資源也被更新佈署。在做更新時也推薦使用 `--atomic` 參數，這可幫助 `charts` 更新失敗後可以進行退回上一個版本。這邊使用的是 `--set` 方式同時也是可以使用 `-f` 來指定要渲染模板的值，以優先順序來說 `--set` 為最高。
```

FYI：https://github.com/cncf/glossary/pull/2035#discussion_r1208790399

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +一般規劃一個服務要佈署在 Kubernetes 上時也許會定義如下資源。但對於要回滾或是修改都會維護這些大量資源，其對於發布的應用程式沒有版本控制的概念。
```suggestion
一般規劃一個服務要部署在 Kubernetes 上時也許會定義如下資源。但對於要退回或是修改都會維護這些大量資源，其對於發布的應用程式沒有版本控制的概念。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +Helm 透過這種設計做到了 Kubernetes 原生無法管理 `yaml` 的問題。到這邊可以了解模板如何渲染，但在渲染前可以對 `charts` 進行格式上驗證，驗證模板中的格式是否正確，但此階段無法確保渲染出來的 Kubernetes 資源可被使用。
```suggestion
Helm 透過這種設計做到了 Kubernetes 原生無法管理 `yaml` 的問題。到這邊可以了解模板如何轉譯，但在轉譯前可以對 `charts` 進行格式上驗證，驗證模板中的格式是否正確，但此階段無法確保轉譯出來的 Kubernetes 資源可被使用。
```

「轉譯」目前是我認爲最好的翻譯方式

FYI：https://breezymove.blogspot.com/2013/12/render.html

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +當一個 `charts` 被定義好之後，應當驗證其模板渲染出來 `yaml` 的完整性。[Kubeconform](https://github.com/yannh/kubeconform) 是一個驗證工具 Kubernetes `yaml` 資源的工具，可以將其導入 CI 流程。
```suggestion
當一個 `charts` 被定義好之後，應當驗證其模板轉譯出來 `yaml` 的完整性。[Kubeconform](https://github.com/yannh/kubeconform) 是一個驗證工具 Kubernetes `yaml` 資源的工具，可以將其導入 CI 流程。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +# -s 指定某個要被渲染的模板
```suggestion
# -s 指定某個要被轉譯的模板
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +對於驗證 `yaml` 完整性來說可能還不夠，如果想要進階的對物件資源進行驗證可以使用 [kube-score](https://github.com/zegl/kube-score) 來實現，其輸出內容會是推薦可實踐的內容，可能相關於安全部分或是可靠性部分。同樣的可以將其導入 CI 流程來強化 charts 所渲染物件是否夠強壯。
```suggestion
對於驗證 `yaml` 完整性來說可能還不夠，如果想要進階的對物件資源進行驗證可以使用 [kube-score](https://github.com/zegl/kube-score) 來實現，其輸出內容會是推薦可實踐的內容，可能相關於安全部分或是可靠性部分。同樣的可以將其導入 CI 流程來強化 charts 所轉譯物件是否夠強壯。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +上面驗證了 `charts` 和 `yaml` 資源，如果想更要在貼近一點現實可以透過單元測試方式驗證渲染的物件內容是不是你期望在 Kubernets 上運行的內容。這邊使用 [helm-unittest](https://github.com/helm-unittest/helm-unittest) 套件來進行單元測試。
```suggestion
上面驗證了 `charts` 和 `yaml` 資源，如果想更要在貼近一點現實可以透過單元測試方式驗證轉譯的物件內容是不是你期望在 Kubernets 上運行的內容。這邊使用 [helm-unittest](https://github.com/helm-unittest/helm-unittest) 套件來進行單元測試。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +是一個將 `charts` 中的資訊渲染成 markdown 檔案的工具。生成的內容包含了 `Chart.yaml` 中的一些資訊或是 `values.yaml` 中定義的值內容，該內容會使用註釋來進行解析。
```suggestion
是一個將 `charts` 中的資訊轉譯成 markdown 檔案的工具。生成的內容包含了 `Chart.yaml` 中的一些資訊或是 `values.yaml` 中定義的值內容，該內容會使用註釋來進行解析。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染 markdown 這流程是從 gotemplate 實作，相似於 `charts` 模板。預設上 helm-docs 有基本的樣式來做渲染，當然也可以透過 `README.md.gotmpl` 檔案進行渲染內容的定義。
```suggestion
轉譯 markdown 這流程是從 gotemplate 實作，相似於 `charts` 模板。預設上 helm-docs 有基本的樣式來做渲染，當然也可以透過 `README.md.gotmpl` 檔案進行轉譯內容的定義。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +`helm-docs` 中可定義的渲染模板可參考此官方[連結](https://github.com/norwoodj/helm-docs#markdown-rendering)，對於渲染來說比較重要的參數是 `--chart-search-root` 和 `--template-files` 如果其提供的預設值不符合場景設計可以進行靈活上的調整。
```suggestion
`helm-docs` 中可定義的轉譯模板可參考此官方[連結](https://github.com/norwoodj/helm-docs#markdown-rendering)，對於轉譯來說比較重要的參數是 `--chart-search-root` 和 `--template-files` 如果其提供的預設值不符合場景設計可以進行靈活上的調整。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +該內容上如果要讓字段有描述，則可以在該字段上以 `# --` 開頭並向後填寫要描述的註釋，最後渲染結果會如下
```suggestion
該內容上如果要讓字段有描述，則可以在該字段上以 `# --` 開頭並向後填寫要描述的註釋，最後轉譯結果會如下
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +如果在 `values.yaml` 是沒有撰寫註釋格式，則最後葉節點會被渲染出來，但是描述部分就有些許空虛了。
```suggestion
如果在 `values.yaml` 是沒有撰寫註釋格式，則最後葉節點會被轉譯出來，但是描述部分就有些許空虛了。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果：
```suggestion
轉譯結果：
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +如果在 `values.yaml` 的根節點字段撰寫註釋，則葉節點部會被渲染，會以根節點物件呈現。
```suggestion
如果在 `values.yaml` 的根節點字段撰寫註釋，則葉節點部會被轉譯，會以根節點物件呈現。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果：
```suggestion
轉譯結果：
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +如果在 `values.yaml` 的根節點和葉節點定義註釋如下，則葉節點有被註釋會被渲染，否則不會。
```suggestion
如果在 `values.yaml` 的根節點和葉節點定義註釋如下，則葉節點有被註釋會被轉譯，否則不會。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +渲染結果：
```suggestion
轉譯結果：
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +另一方面，`charts` 可以被版控，也可以針對每個環境使用不同的 `values.yaml` 來做渲染，減少了管理多環境的資源，同時對於現今的 GitOps 概念來說可以做一個很好的整合。
```suggestion
另一方面，`charts` 可以被版控，也可以針對每個環境使用不同的 `values.yaml` 來做轉譯，減少了管理多環境的資源，同時對於現今的 GitOps 概念來說可以做一個很好的整合。
```

2023-09-17 03:21 UTC, tico88612 commented on docs/self-paced-labs/helm-charts/index.md
> +# --     Configure the healthcheck for the application
```suggestion
# -- Configure the healthcheck for the application
```

2023-09-17 14:36 UTC, CCH0124 commented
> 非常感謝前面修正，不過我這裡覺得還有幾個需要修改：
> 
> 1. 翻譯修正
> 
> `回滾` => `退回` [cncf/glossary#2035 (comment)](https://github.com/cncf/glossary/pull/2035#discussion_r1208790399) `渲染` => `轉譯` https://breezymove.blogspot.com/2013/12/render.html
> 
> 2. 文章連結命名
> 
> 資料夾連結不要直接命名為 `helm-charts`（會以為只有 Helm Chart 教學），建議名稱為 `quarkus-with-helm-charts` 等其他命名。
> 
> 3. 壓縮成同一個 commit 即可，感謝！

Hi, @tico88612  壓縮成同一個 commit 是指第 1、2 點使用同一個 commit 修正嗎 ?

2023-09-17 14:40 UTC, tico88612 commented
> > 非常感謝前面修正，不過我這裡覺得還有幾個需要修改：
> > 
> > 1. 翻譯修正
> > 
> > `回滾` => `退回` [cncf/glossary#2035 (comment)](https://github.com/cncf/glossary/pull/2035#discussion_r1208790399) `渲染` => `轉譯` https://breezymove.blogspot.com/2013/12/render.html
> > 
> > 2. 文章連結命名
> > 
> > 資料夾連結不要直接命名為 `helm-charts`（會以為只有 Helm Chart 教學），建議名稱為 `quarkus-with-helm-charts` 等其他命名。
> > 
> > 3. 壓縮成同一個 commit 即可，感謝！
> 
> Hi, @tico88612 壓縮成同一個 commit 是指第 1、2 點使用同一個 commit 修正嗎 ?

您好，就是這次貢獻您只需要有 `feat: quarkus with helm charts` 一個 commit 即可，不需要包含 fix 中間的修改過程。

2023-09-18 12:55 UTC, CCH0124 commented
@tico88612  已經進行更新

2023-09-18 14:00 UTC, tico88612 requested changes
1. 容器鏡像 => 容器映像檔
2. 註釋 => 註解 （資訊領域通常使用註解居多，annotation 也是寫註解）
3. 字段 => 欄位 （中國翻譯 Field 為字段，但在臺灣中文應該稱呼為欄位）
4. 「渲染」部分沒有更改到
5. 統一「佈署」或是「部署」，依照 Glossary 翻譯最好統一為：「部署」
6. 這裡看到的 PR 是 3 個 commit，請 fixup 成 1 個即可。

部署 FYI:
- https://github.com/cncf/glossary/pull/2035/files#diff-53ecee9a21d42345c283ac2cf7308043c06d4823a2f72ebaa186b35df1d3f50eR2

Git fixup:
- https://www.cythilya.tw/2018/06/04/git-rebase-squash-vs-fixup/
- https://github.com/twtrubiks/Git-Tutorials#fixup

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +渲染 markdown 這流程是從 gotemplate 實作，相似於 `charts` 模板。預設上 helm-docs 有基本的樣式來做渲染，當然也可以透過 `README.md.gotmpl` 檔案進行轉譯內容的定義。
```suggestion
轉譯 markdown 這流程是從 gotemplate 實作，相似於 `charts` 模板。預設上 helm-docs 有基本的樣式來做轉譯，當然也可以透過 `README.md.gotmpl` 檔案進行轉譯內容的定義。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +- `Release` Kubernetes Cluster 中部署的包
需要統一 `佈署` 或是 `部署`，依照 Glossary 翻譯最好統一為：`部署`

https://github.com/cncf/glossary/pull/2035/files#diff-53ecee9a21d42345c283ac2cf7308043c06d4823a2f72ebaa186b35df1d3f50eR2

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +Helm 是一個管理 Kubernetes 資源的打包工具，其產出單元可以稱為 `charts`，類似於容器鏡像或是 Ubuntu 中的 apt 管理工具，因此它是可以被建立或是刪除。其同時也是 CNCF [Application Definition & Image Build](https://landscape.cncf.io/card-mode?category=application-
container image? container mirror?
```suggestion
Helm 是一個管理 Kubernetes 資源的打包工具，其產出單元可以稱為 `charts`，類似於容器映像檔或是 Ubuntu 中的 apt 管理工具，因此它是可以被建立或是刪除。其同時也是 CNCF [Application Definition & Image Build](https://landscape.cncf.io/card-mode?category=application-definition-image-build&grouping=category) 中的一員。常見類似的有 [Kustomize](https://kustomize.io/) 等。
```

https://philipzheng.gitbook.io/docker_practice/basic_concept/image

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +這邊發現一些 `CRITICAL` 訊息，這表示 `kube-score` 建議你要做像是不使用 latest 鏡像標籤或是希望有 `PodDisruptionBudget` 的物件等。在 CI 中出現了 `CRITICAL` 會是以不通過收場。如果假設在環境上沒有打算實現 `PodDisruptionBudget` 或是 `NetworkPolicy` 資源，我們可以透過 `--disable
```suggestion
這邊發現一些 `CRITICAL` 訊息，這表示 `kube-score` 建議你要做像是不使用 latest 映像檔標籤或是希望有 `PodDisruptionBudget` 的物件等。在 CI 中出現了 `CRITICAL` 會是以不通過收場。如果假設在環境上沒有打算實現 `PodDisruptionBudget` 或是 `NetworkPolicy` 資源，我們可以透過 `--disable-ignore-checks-annotations` 或是 Kubernetes 中 `annotations` 欄位使用 `kube-score/ignore` 來實現必驗證的動作，官方提供的[清單](https://github.com/zegl/kube-score/blob/master/README_CHECKS.md)。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +- path: 會是參照 Kubernetes 物件資源上內容，通常會精準指向某個物件中字段。可以想像是透過 `kubectl get` 某物件然後使用 `jsonpath` 來自定義輸出。
```suggestion
- path: 會是參照 Kubernetes 物件資源上內容，通常會精準指向某個物件中欄位。可以想像是透過 `kubectl get` 某物件然後使用 `jsonpath` 來自定義輸出。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +- value: 期望 path 上的值，但這通常用於 Kubernetes 上的字段指對應一個值使用。
```suggestion
- value: 期望 path 上的值，但這通常用於 Kubernetes 上的欄位指對應一個值使用。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +該內容上如果要讓字段有描述，則可以在該字段上以 `# --` 開頭並向後填寫要描述的註釋，最後轉譯結果會如下
```suggestion
該內容上如果要讓欄位有描述，則可以在該欄位上以 `# --` 開頭並向後填寫要描述的註解，最後轉譯結果會如下
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +如果在 `values.yaml` 的根節點字段撰寫註釋，則葉節點部會被渲染，會以根節點物件呈現。
部會 => 不會(?)
```suggestion
如果在 `values.yaml` 的根節點欄位撰寫註解，則葉節點不會被轉譯，會以根節點物件呈現。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +下面是一個測試 `deployment.yaml` 的內容。在 `asserts` 中用了 `equal`、`isNotEmpty`、`contains` 等關鍵字，但重點在於 `path` 其就是用來對應真實佈署資源的字段。
```suggestion
下面是一個測試 `deployment.yaml` 的內容。在 `asserts` 中用了 `equal`、`isNotEmpty`、`contains` 等關鍵字，但重點在於 `path` 其就是用來對應真實佈署資源的欄位。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +`_helpers.tpl` 這個檔案可以定義共用的模板，以此範例來說定義了一個共用註釋的方法，如下。該 `web-app.annotation` 是方法名稱，其用 `define` 關鍵字進行定義。
```suggestion
`_helpers.tpl` 這個檔案可以定義共用的模板，以此範例來說定義了一個共用註解區塊的方法，如下。該 `web-app.annotation` 是方法名稱，其用 `define` 關鍵字進行定義。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +{{/* # 註釋塊
```suggestion
{{/* # 註解區塊
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +是一個將 `charts` 中的資訊轉譯成 markdown 檔案的工具。生成的內容包含了 `Chart.yaml` 中的一些資訊或是 `values.yaml` 中定義的值內容，該內容會使用註釋來進行解析。
```suggestion
是一個將 `charts` 中的資訊轉譯成 markdown 檔案的工具。生成的內容包含了 `Chart.yaml` 中的一些資訊或是 `values.yaml` 中定義的值內容，該內容會使用註解來進行解析。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +如果在 `values.yaml` 是沒有撰寫註釋格式，則最後葉節點會被轉譯出來，但是描述部分就有些許空虛了。
```suggestion
如果在 `values.yaml` 是沒有撰寫註解格式，則最後葉節點會被轉譯出來，但是描述部分就有些許空虛了。
```

2023-09-18 14:00 UTC, tico88612 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +如果在 `values.yaml` 的根節點和葉節點定義註釋如下，則葉節點有被註釋會被轉譯，否則不會。
```suggestion
如果在 `values.yaml` 的根節點和葉節點定義註解如下，則葉節點有被註解會被轉譯，否則不會。
```

2023-09-19 01:06 UTC, CCH0124 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +Helm 是一個管理 Kubernetes 資源的打包工具，其產出單元可以稱為 `charts`，類似於容器鏡像或是 Ubuntu 中的 apt 管理工具，因此它是可以被建立或是刪除。其同時也是 CNCF [Application Definition & Image Build](https://landscape.cncf.io/card-mode?category=application-
container image，我再修正

2023-09-19 01:07 UTC, CCH0124 commented on docs/self-paced-labs/quarkus-with-helm-charts/index.md
> +如果在 `values.yaml` 的根節點字段撰寫註釋，則葉節點部會被渲染，會以根節點物件呈現。
是不會才對

2023-09-20 05:55 UTC, CCH0124 commented
@tico88612 我有做 `Squash` 但不確定有沒有正確 我第一次使用這種指令，有誤在麻煩修正

2023-09-22 00:46 UTC, pichuang commented
@CCH0124 建議可以用 GitHub Desktop 做 Squash，相當好用

https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop

2023-09-22 02:07 UTC, tico88612 commented
> @tico88612 我有做 `Squash` 但不確定有沒有正確 我第一次使用這種指令，有誤在麻煩修正

看到 commits 頁面只要不是寫上 1，就代表需要再修改

https://github.com/cloud-native-taiwan/Infra-Labs-Docs/pull/48/commits

2023-09-22 02:56 UTC, ydFu commented
當您想要將多個 Git commit 合併成一個時，您可以使用 Git 的互動式重新基礎（interactive rebase）功能。以下是一個簡單的步驟：

1. 打開終端機，切換到您的 Git 存儲庫所在的目錄。
2. 執行以下命令來啟動互動式重新基礎：
      ```
   git rebase -i HEAD~2
   ```
    上述命令中的 `HEAD~2` 表示您想要重新基礎的最近兩個 commit。如果您想要合併不同的 commit 數量，可以將數字修改為相應的值。
3. Git 會打開一個文本編輯器，列出要重新基礎的 commit 歷史。每個 commit 都有一個前面的文字，通常是 "pick"，表示要保留該 commit。將您想要合併的第二個 commit 的文字從 "pick" 修改為 "squash" 或 "s"（表示合併）。
4. 保存並關閉文本編輯器。
5. Git 會再次打開文本編輯器，讓您編輯合併後的 commit 訊息。您可以保留其中一個 commit 的訊息，或者自行編輯以創建新的訊息。
6. 再次保存並關閉文本編輯器。
7. Git 會將多個 commit 合併成一個，並且創建一個新的 commit。

2023-09-27 13:47 UTC, CCH0124 commented
@tico88612 我有做壓縮的動作但不知道為何結果都變不了一個 commit。我是對 `d9d6799a` commit 進行 rebase
```bash
git -i rebase d9d6799a
```

2023-09-27 13:49 UTC, ching-kuo commented
@CCH0124 你要不要針對 upstream branch 先做 rebase 然後再 squash？

2023-09-27 14:19 UTC, tico88612 commented
@CCH0124 或者另外一種方式就是把你現在變更的檔案，先 copy 出去，把 local branch `feat/helm-chart` 先刪除，從 main 重開一條 `feat/helm-chart`，把原本的檔案套用回來，再重新 force push。

2023-09-29 03:44 UTC, CCH0124 commented
> @CCH0124 或者另外一種方式就是把你現在變更的檔案，先 copy 出去，把 local branch `feat/helm-chart` 刪除，從 main 重開一條 `feat/helm-chart`，把原本的檔案套用回來，再重新 force push。
> 
> 麻煩可能要把 PR 標題修改一下

這樣可以了，它變成一個 commit

2023-09-29 03:56 UTC, tico88612 approved these changes

2023-09-29 03:58 UTC, tico88612 commented
LGTM, thanks for the contribution!

2023-09-29 03:58 UTC, merged