feat: add Quarkus integrates Vault and Secrets Store CSI Driver
cloud-native-taiwan/Infra-Labs-Docs pull request #59
Opened 2023-12-15 15:47 UTC by CCH0124

1. Quarkus 整合 Vault 與 Secrets Store CSI Driver
2. Vault 配置 Kubernetes auth

2023-12-17 02:51 UTC, ching-kuo reviewed
Some comments

2023-12-17 02:51 UTC, ching-kuo commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +Vault 是一個可將機密資訊集中化管理的一個平台，不論是憑證、密碼等。再者要存取這些資訊都是要經過一層身份驗證才能獲取儲存在 Vault 服務上的機密資訊。專案整合 Vault 服務能夠降低敏感數據暴露風險、集中管理提高生產效率等。本文章會透過第三方工具整合 Vault 實現無入侵程式碼，其優勢可以將不熟悉的專案進行整合。
都是要 --> 都要

2023-12-17 02:51 UTC, ching-kuo commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +## 參考資源
`資料`感覺比較好一點？

2023-12-17 02:51 UTC, ching-kuo commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +## 建立環境
如果標準的 Kubernetes Cluster 也可以使用的話我覺得可以加註一下。

2023-12-18 03:06 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +## 參考資源
參考資源變成參考資料嗎

2023-12-18 03:07 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +## 建立環境
這是一個好的加註

2023-12-23 13:01 UTC, CCH0124 commented
> Some comments

已修正一些語句

2023-12-24 09:23 UTC, ching-kuo approved these changes
LGTM, let's wait for another review

2023-12-27 08:25 UTC, tico88612 requested changes
這裡先做個初步 Review，部分詞語需要修改。

- `集群` => `叢集`
- `配置` => `設定`
- `POD` => `Pod`

部分專有名詞詳情參閱：https://glossary.cncf.io/zh-tw/

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +透過 `kubernetes.io/service-account-token` 建立的長期令牌將賦予給 Vault 服務並與 quarkus-cluster 交互。如果使用短期令牌，一旦 POD 或 `ServiceAccount` 被刪除 Kubernetes 就會撤銷它，或者如果令牌過期後，Vault 將無法再使用該令牌與 kubernetes API。但，長期令牌沒有短期令牌的安全性，但
```suggestion
透過 `kubernetes.io/service-account-token` 建立的長期令牌將賦予給 Vault 服務並與 quarkus-cluster 互動。如果使用短期令牌，一旦 Pod 或 `ServiceAccount` 被刪除 Kubernetes 就會撤銷它，或者如果令牌過期後，Vault 將無法再使用該令牌與 kubernetes API。但，長期令牌沒有短期令牌的安全性，但兩方式都能整合。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +最後透過部署 Quarkus 資源驗證，部署檔案透過此[鏈接](https://github.com/CCH0124/vault-with-quarkus/blob/main/secret-csi-vault/k8s/deployment.yaml)獲取檔案部署。
```suggestion
最後透過部署 Quarkus 資源驗證，部署檔案透過此[連結](https://github.com/CCH0124/vault-with-quarkus/blob/main/secret-csi-vault/k8s/deployment.yaml)取得。
```

修正簡體語法，贅字。

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +到這邊可以知道如何透過一個 Vault 服務整合外部的 Kubernetes。並透過 Quarkus 框架所提供的 Vault API 進行交互，配置如下。
```suggestion
到這邊可以知道如何透過一個 Vault 服務整合外部的 Kubernetes。並透過 Quarkus 框架所提供的 Vault API 進行互動，設定如下。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +本範例的 Quarkus 應用程式成功連線後，在 Vault 服務可以看到其日誌。POD 中容器應用程式將透過 Vault API `/v1/auth/quarkus-cluster/login` 進行登入，並驗證來自 `serviceAccount` 令牌，成功後再透過 Vault API `/v1/kv/data/quarkus/vault-demo` 獲取 `secrets` 資源。
```suggestion
本範例的 Quarkus 應用程式成功連線後，在 Vault 服務可以看到其日誌。Pod 中容器應用程式將透過 Vault API `/v1/auth/quarkus-cluster/login` 進行登入，並驗證來自 `serviceAccount` 令牌，成功後再透過 Vault API `/v1/kv/data/quarkus/vault-demo` 獲取 `secrets` 資源。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +安裝完後每個節點都會有一個 POD，該 POD 是由 `DaemonSet` 所產生。
```suggestion
安裝完後每個節點都會有一個 Pod，該 Pod 是由 `DaemonSet` 所產生。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +安裝 [vault-csi-provider](https://github.com/hashicorp/vault-csi-provider)，以讓 Secrets Store CSI 取得儲存在 Vault 中的資訊，並使用 Secrets Store CSI 介面將它們掛載到 Kubernetes POD 中。
```suggestion
安裝 [vault-csi-provider](https://github.com/hashicorp/vault-csi-provider)，以讓 Secrets Store CSI 取得儲存在 Vault 中的資訊，並使用 Secrets Store CSI 介面將它們掛載到 Kubernetes Pod 中。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +如果不安裝 vault-csi-provider，則會導致 Secrets Store CSI 介面不知道如何整合 Vault，在啟動 POD 時會出現以下訊息 `provider not found: provider "vault"`。
```suggestion
如果不安裝 vault-csi-provider，則會導致 Secrets Store CSI 介面不知道如何整合 Vault，在啟動 Pod 時會出現以下訊息 `provider not found: provider "vault"`。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +首先礙於 K3d 建立環境，這邊 Vault 使用 NodePort 方式將 Vault 服務給導出。讀者如有不用 ＮodePort 方式，在不吝嗇分享。
```suggestion
首先礙於 K3d 建立環境，這邊 Vault 使用 NodePort 方式將 Vault 服務給導出。讀者如有不用 NodePort 方式，在不吝嗇分享。
```

應該為半形

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +2. 將 POD 建立的 ServiceAccount 令牌掛載至容器中
```suggestion
2. 將 Pod 建立的 ServiceAccount 令牌掛載至容器中
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +建立一個可透過 Secret Store CSI 提供的 CRD 來存取 Vault 中 KV 資源。預設上，KV 資源丟什麼值就取什麼值。
前面寫 Secrets Store CSI，這裡變成 Secret Store CSI，這兩者是否有差異？

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +上面 ENV 或 FILE 簡易的流程是 kubelet 在 POD volume 掛載期間調用 CSI 驅動程式。因此，在 POD 啟動後，後續更改不會觸發對該掛載或 Kubernetes 金鑰中內容的更新。那這可能是用第三方套件像是 [Reloader](https://github.com/stakater/Reloader) 或是應用程式自行實現。
```suggestion
上面 ENV 或 FILE 簡易的流程是 kubelet 在 Pod volume 掛載期間調用 CSI 驅動程式。因此，在 Pod 啟動後，後續更改不會觸發對該掛載或 Kubernetes 金鑰中內容的更新。那這可能是用第三方套件像是 [Reloader](https://github.com/stakater/Reloader) 或是應用程式自行實現。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +如果上面範例配置有像是找不到 Vault 中定義的 Key 問題則 POD 會處於 ContainerCreating 狀態，如下
```suggestion
如果上面範例配置有像是找不到 Vault 中定義的 Key 問題則 Pod 會處於 ContainerCreating 狀態，如下
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +宣告 K3d 配置
```suggestion
宣告 K3d 設定
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +使用上述配置建立模擬 kubernetes 環境
```suggestion
使用上述設定檔建立模擬 kubernetes 環境
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +配置 Quarkus Kubernetes 集群，對應本實驗[專案](https://raw.githubusercontent.com/CCH0124/vault-with-quarkus/main/secret-csi-vault/k3d/config.yaml)。
```suggestion
設定 Quarkus Kubernetes 集群，對應本實驗[專案](https://raw.githubusercontent.com/CCH0124/vault-with-quarkus/main/secret-csi-vault/k3d/config.yaml)。
```

2023-12-27 08:25 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +Quarkus 專案會部署至 Quarkus Kubernetes 集群，但 Vault 服務為另一個叫 vault-cluster 的環境。下面將會演飾如何從 Vault 配置基於 Kubernetes 的認證，以讓 quarkus-cluster 中 quarkus 應用程式存取。
```suggestion
Quarkus 專案會部署至 Quarkus Kubernetes 集群，但 Vault 服務為另一個叫 vault-cluster 的環境。下面將會示範如何從 Vault 設定基於 Kubernetes 的認證，以讓 quarkus-cluster 中 quarkus 應用程式存取。
```

2024-01-02 13:18 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +建立一個可透過 Secret Store CSI 提供的 CRD 來存取 Vault 中 KV 資源。預設上，KV 資源丟什麼值就取什麼值。
secrets 才對

2024-01-03 01:47 UTC, CCH0124 commented
如果我要在文章內在補充幾段話是可行的嗎

2024-01-03 01:51 UTC, tico88612 commented
直接加入即可，之後會再重新 review。

2024-01-03 01:54 UTC, tico88612 commented
BTW，詞語部分我剛剛看還是有些沒有改到，你可能要用 `ctrl + f` 去搜尋取代。

2024-01-03 12:33 UTC, CCH0124 commented
> * 設定
已將集群與配置兩名詞進行取代

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +使用上述設定檔建立模擬 kubernetes 環境
```suggestion
使用上述設定檔建立模擬 Kubernetes 環境
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +宣告 K3d 設定
下面建立 cluster 連結有附上設定檔連結，但這裡沒有的原因？

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +透過 `kubernetes.io/service-account-token` 建立的長期令牌將賦予給 Vault 服務並與 quarkus-cluster 互動。如果使用短期令牌，一旦 Pod 或 `ServiceAccount` 被刪除 Kubernetes 就會撤銷它，或者如果令牌過期後，Vault 將無法再使用該令牌與 kubernetes API。但，長期令牌沒有短期令牌的安全性，但
```suggestion
透過 `kubernetes.io/service-account-token` 建立的長期令牌將賦予給 Vault 服務並與 quarkus-cluster 互動。如果使用短期令牌，一旦 Pod 或 `ServiceAccount` 被刪除 Kubernetes 就會撤銷它，或者如果令牌過期後，Vault 將無法再使用該令牌與 Kubernetes API。但，長期令牌沒有短期令牌的安全性，但兩方式都能整合。
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +該 Secret store CSI 還能夠整合其它第三方服務可參考[官方資訊](https://secrets-store-csi-driver.sigs.k8s.io/providers)。本實驗會整合 Vault。
```suggestion
該 Secrets store CSI 還能夠整合其它第三方服務可參考[官方資訊](https://secrets-store-csi-driver.sigs.k8s.io/providers)。本實驗會整合 Vault。
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +準備好上面的鍵值對後，將透過 Secret Store CSI 提供的 CRD 進行 Vault 存取宣告，這邊會分成基於 ENV 和 FILE 來做分享。
```suggestion
準備好上面的鍵值對後，將透過 Secrets Store CSI 提供的 CRD 進行 Vault 存取宣告，這邊會分成基於 ENV 和 FILE 來做分享。
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +- Secret Store CSI chart version: 1.4.0
```suggestion
- Secrets Store CSI chart version: 1.4.0 
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +...
建議註解明確一點，簡略說明如何相互對應（或者直接把註解去掉）
```suggestion
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GREETING_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: quarkus
                  key: greeting.message
...
          volumeMounts:
...
          - name: vault-secret-env
            mountPath: "/mnt/secret s-store"
            readOnly: true
...
      volumes:
...
      - name: vault-secret-env
        csi:
          driver: 'secrets-store.csi.k8s.io'
          readOnly: true
          volumeAttributes:
            secretProviderClass: 'quarkus-demo-env'
...
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +本章透過單一 Vault 服務整合多個叢集，並整合 Kubernetes 身份驗證來讓 Vault 存取 Kubernetes 叢集，同樣的 Vault 支援多種認證，可依照場景進行整合。最後透過 Secrets Store CSI Driver 方式實現無侵入方式讓應用程式與 Vault 進行整合。雖然目前對於自動更新支援度不是很好，但該功能透過社群會逐漸穩定，但其對於不熟悉專案與 Vault
```suggestion
本章透過單一 Vault 服務整合多個叢集，並整合 Kubernetes 身份驗證來讓 Vault 存取 Kubernetes 叢集，同樣的 Vault 支援多種認證，可依照場景進行整合。最後透過 Secrets Store CSI Driver 方式實現無侵入方式讓應用程式與 Vault 進行整合。雖然目前對於自動更新支援度不是很好，但該功能透過社群會逐漸穩定，但其對於不熟悉專案與 Vault 整合是一個好的方式。當然，Secrets Store CSI Driver 並非是一種唯一的解決方案，會選擇也許是容易理解、設定容易。
```

2024-01-13 01:56 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +- [secrets store csi driver](https://secrets-store-csi-driver.sigs.k8s.io/)
專有名詞建議使用官方寫法

```suggestion
- [Kubernetes - Auth Methods | Vault | HashiCorp Developer](https://developer.hashicorp.com/vault/docs/auth/kubernetes)
- [Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/)
```

2024-01-13 01:56 UTC, tico88612 commented on sidebars.js
> +        'self-paced-labs/vault-secret-store-csi-with-quarkus/index'
按照上次 review 說明應為 Secret Store CSI，此故這裡改為 secrets
```suggestion
        'self-paced-labs/vault-secrets-store-csi-with-quarkus/index'
```

2024-01-13 15:33 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +宣告 K3d 設定
下面直接描述其 K3d 設定

2024-01-13 15:47 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +...
`mountPath: "/mnt/secret s-store"` 這邊多的空白有做修正

2024-01-13 15:48 UTC, CCH0124 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +宣告 K3d 設定
下面有宣告配置，但我覺得我還是補上去好了

2024-01-13 15:59 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +本實驗環境的建置可應用於標準 Kubernetes 叢集。本實驗所使用的專案[連接](https://github.com/CCH0124/vault-with-quarkus/tree/d939a7b057bf7688b9ee6162fe2cf4fa0365db9d/secret-csi-vault)。
typo

```suggestion
本實驗環境的建置可應用於標準 Kubernetes 叢集。本實驗所使用的專案[連結](https://github.com/CCH0124/vault-with-quarkus/tree/d939a7b057bf7688b9ee6162fe2cf4fa0365db9d/secret-csi-vault)。
```

2024-01-13 15:59 UTC, tico88612 commented on docs/self-paced-labs/vault-secret-store-csi-with-quarkus/index.md
> +在 quarkus-cluster 叢集中手動建置一個給 `ServiceAccount` 的長期 API 令牌，並透過 `kubernetes.io/service-account.name` 建立一個新 `Secret` 物件，內容包含 `ca.crt`、`token` 等欄位。有關手動建立長期令牌可參閱[官方](https://kubernetes.io/docs/tasks/config
```suggestion
在 quarkus-cluster 叢集中手動建置一個給 `ServiceAccount` 的長期 API 令牌，並透過 `kubernetes.io/service-account.name` 建立一個新 `Secret` 物件，內容包含 `ca.crt`、`token` 等欄位。有關手動建立長期令牌可參閱[官方文件](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount)。
```

2024-01-14 02:30 UTC, tico88612 requested changes

2024-01-14 02:30 UTC, tico88612 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +![](https://camo.githubusercontent.com/e7f39411f46e3d71c3e64076764fc4f21230d5e28cb3d0faf868c38dea74a7f2/68747470733a2f2f736563726574732d73746f72652d6373692d6472697665722e736967732e6b38732e696f2f696d6
剛剛瀏覽的時候，這張是死圖，需要刪除或修正

2024-01-14 04:33 UTC, CCH0124 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +![](https://camo.githubusercontent.com/e7f39411f46e3d71c3e64076764fc4f21230d5e28cb3d0faf868c38dea74a7f2/68747470733a2f2f736563726574732d73746f72652d6373692d6472697665722e736967732e6b38732e696f2f696d6
更新其 link

2024-01-14 04:50 UTC, tico88612 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +![](https://camo.githubusercontent.com/e7f39411f46e3d71c3e64076764fc4f21230d5e28cb3d0faf868c38dea74a7f2/68747470733a2f2f736563726574732d73746f72652d6373692d6472697665722e736967732e6b38732e696f2f696d6
能否把這張圖抓下來？會擔心原本官網圖片會變成死連結

2024-01-14 04:54 UTC, tico88612 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +對於 Secrets Store CSI Driver 基本上支援所有 Kubernetes Secret 類型，個人覺得將私有鏡像存取的令牌使用 base64 編碼並將其整合至 Vault，最後使用 Secrets Store CSI Driver 將其私有鏡像存取的令牌進行抓取並載入至 Pod 讓其生命週期由 Secrets Store CSI Driver 進行控管，這樣減少了不必要的資訊
私有鏡像存取 這句話沒看懂？mirror 還是 image？

2024-01-14 04:54 UTC, tico88612 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +Secrets Store CSI Driver 官方提供了下圖架構圖。kubelet 會呼叫 Secrets Store CSI Driver，在透過 `SecretProviderClass` 檢索內容。不過其會隨著 Pod 的刪除而刪除，但這不見得是壞事，畢竟資源它幫你清，減少垃圾資源的存在。更多的細節可至官方進行[翻閱](https://secrets-store-csi-driver.
typo
```suggestion
Secrets Store CSI Driver 官方提供了下圖架構圖。kubelet 會呼叫 Secrets Store CSI Driver，再透過 `SecretProviderClass` 檢索內容。不過其會隨著 Pod 的刪除而刪除，但這不見得是壞事，畢竟資源它幫你清，減少垃圾資源的存在。更多的細節可至官方進行[翻閱](https://secrets-store-csi-driver.sigs.k8s.io/concepts)。
```

2024-01-14 04:59 UTC, CCH0124 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +對於 Secrets Store CSI Driver 基本上支援所有 Kubernetes Secret 類型，個人覺得將私有鏡像存取的令牌使用 base64 編碼並將其整合至 Vault，最後使用 Secrets Store CSI Driver 將其私有鏡像存取的令牌進行抓取並載入至 Pod 讓其生命週期由 Secrets Store CSI Driver 進行控管，這樣減少了不必要的資訊
private register 中的 image

2024-01-14 05:15 UTC, tico88612 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +對於 Secrets Store CSI Driver 基本上支援所有 Kubernetes Secret 類型，個人覺得將私有鏡像存取的令牌使用 base64 編碼並將其整合至 Vault，最後使用 Secrets Store CSI Driver 將其私有鏡像存取的令牌進行抓取並載入至 Pod 讓其生命週期由 Secrets Store CSI Driver 進行控管，這樣減少了不必要的資訊
繁體中文的 docker image 多數都是寫「映像檔」而非「鏡像」

2024-01-14 05:30 UTC, CCH0124 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +![](https://camo.githubusercontent.com/e7f39411f46e3d71c3e64076764fc4f21230d5e28cb3d0faf868c38dea74a7f2/68747470733a2f2f736563726574732d73746f72652d6373692d6472697665722e736967732e6b38732e696f2f696d6
可以

2024-01-14 05:31 UTC, CCH0124 commented on docs/self-paced-labs/vault-secrets-store-csi-with-quarkus/index.md
> +對於 Secrets Store CSI Driver 基本上支援所有 Kubernetes Secret 類型，個人覺得將私有鏡像存取的令牌使用 base64 編碼並將其整合至 Vault，最後使用 Secrets Store CSI Driver 將其私有鏡像存取的令牌進行抓取並載入至 Pod 讓其生命週期由 Secrets Store CSI Driver 進行控管，這樣減少了不必要的資訊
這部分我在修改成 映像檔

2024-01-14 08:28 UTC, tico88612 commented
LGTM，請合併成一個 commit 即可。

2024-01-14 12:35 UTC, closed without merging