Add kubeadm lab
cloud-native-taiwan/Infra-Labs-Docs pull request #65
Opened 2024-02-18 05:15 UTC by cdxvy30

This commit provides lab of using `kubeadm` to install K8s on OpenStack. The process includes open VMs on OpenStack, installing container runtime, `kubeadm`, `kubectl`, `kubelet`, etc.

2024-02-25 09:01 UTC, ching-kuo requested changes, later dismissed
Some quick comments

2024-02-25 09:01 UTC, ching-kuo commented on docs/self-paced-labs/kubeadm/index.md
> +這個步驟是為了確保 Kubernetes 在辨認 Node 的時候有唯一值可作參考，如果 Node 間有相同的 MAC address 或 `product__uuid` 可能會造成安裝失敗。
是不是多了一個底線？

2024-02-25 09:01 UTC, ching-kuo commented on docs/self-paced-labs/kubeadm/index.md
> +echo 1 > /proc/sys/net/ipv4/ip_forward
不太確定沒寫進 `sysctl.conf` 的設定 reboot 後還在不在，可以確認一下

2024-02-25 09:01 UTC, ching-kuo commented on docs/self-paced-labs/kubeadm/index.md
> +另外，訊息中最後一段有提供加入 Worker Node 用的指令 (`kebeadm join`)，可以先將該段指令複製下來，用來在工作節點上執行。
typo

2024-02-25 09:07 UTC, ching-kuo commented
如果可以我覺得可以加上安裝 OpenStack Cloud Provider 等的步驟，畢竟你的 Prometheus lab 有提到要用到 Cinder CSI driver。或是加在 note 裡面去官方文件連結也可以。

2024-02-26 14:07 UTC, cdxvy30 commented on docs/self-paced-labs/kubeadm/index.md
> +echo 1 > /proc/sys/net/ipv4/ip_forward
測試過 reboot 之後會不見，那這邊另外註明永久修改的話可直接把 `/etc/sysctl.conf` 的 `#net.ipv4.ip_forward=1` 註解拿掉嗎？或直接改為永久修改的版本？

2024-03-02 18:14 UTC, tico88612 requested changes
Initial review.

- 命令權限有點混亂，請以 `$` (regular) 和 `#` (root) 做區分。
- log 輸出 code block 不建議使用 bash，它們並非命令。
- VM 網段敘述矛盾，前面是 `192.168.100.101`，後面是 `192.168.200.101`？

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +apt install -y -t buster-backports libseccomp2 || apt update -y -t buster-backports libseccomp2
```suggestion
$ sudo su
# echo 'deb http://deb.debian.org/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
# apt update
# apt install -y -t buster-backports libseccomp2 || apt update -y -t buster-backports libseccomp2
```

如果會有 regular 權限和 root 權限，開頭分別用 `$` 和 `#` 做區分。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131
如果會有 regular 權限和 root 權限，開頭分別用 `$` 和 `#` 做區分。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sou
`$OS` 如何來的？此篇前後文中並沒有說明相關設定。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +exit
如果會有 regular 權限和 root 權限，開頭分別用 $ 和 # 做區分。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +安裝完 container runtime 相關的套件後，記得將 container runtime interface 的服務啟動，否則後續的 kubeadm 初始化會沒辦法執行。(要有 container runtime 才能跑起 K8s 的資源)
最後一句話 `(要有 container runtime 才能跑起 K8s 的資源)`，有點不明白
`資源` 的意思，因為通常資源會是指 `CPU`、`Memory` 等，如果不是指這意思會需要改寫一下。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +接下來就可以安裝最重要的 `kubeadm` 工具，以及操作 Kubernetes 叢集常用到的 `kubectl` 和在各個節點背景作為 agent 運作的 `kubelet`，根據官方文件依下列指令進行安裝:
建議這裡附上 v1.27 官方文件（前面有附，後面統一一下）。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +sudo apt-mark hold kubelet kubeadm kubectl
如果會有 regular 權限和 root 權限，開頭分別用 $ 和 # 做區分。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +echo 1 > /proc/sys/net/ipv4/ip_forward
我建議需要更改的全部寫入 `/etc/sysctl.conf`。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +安裝順利的話，就可以看到下列訊息，代表 Kubernetes 的 Control Plane 的各個元件已經順利跑起來。
一句話建議不要有兩個重複的詞和重複兩次「的」，因此可修改為：
```suggestion
安裝順利的話，就可以看到下列訊息，代表 Kubernetes 的 Control Plane 各個元件已經正常啟動。
```

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +```bash
log 輸出的 code block 建議不要用 bash。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +```bash
log 輸出的 code block 建議不要用 bash。

2024-03-02 18:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +sudo kubeadm init --apiserver-advertise-address=192.168.200.101 --pod-network-cidr=10.244.0.0/16
與 L26 前後矛盾，前面網段為 `192.168.100.101` 怎麼這裡變成 `192.168.200.101`

2024-03-30 17:07 UTC, tico88612 reviewed
Second review

2024-03-30 17:07 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +$ sudo su
我觀看文章時，突然想到可能會跟註解混淆。
你覺得有沒有比較好的呈現方式？

2024-03-30 17:07 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +因為我們在 OpenStack 上是以 Ubuntu 作為作業系統，在官方文件上有[對應的安裝方式](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems)。接下來的指令需要以 root 權限執行:
近期看文件有改安裝方式，舊版放在 install-legacy.md 裡面了。
```suggestion
因為我們在 OpenStack 上是以 Ubuntu 作為作業系統，在官方文件上有[對應的安裝方式](https://github.com/cri-o/cri-o/blob/main/install-legacy.md#apt-based-operating-systems)。接下來的指令需要以 root 權限執行:
```

2024-03-30 17:07 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +在繼續安裝 container runtime 前，我們需要先指定要安裝的 CRI-O 版本及 OS，這邊因為預計安裝的 CRI-O 版本為 `1.24` ，以及在 Infra Lab 建立的雲實例 OS 是 `Ubuntu 22.04`，因此根據[官方文件](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operat
近期看文件有改安裝方式，舊版放在 install-legacy.md 裡面了。
```suggestion
在繼續安裝 container runtime 前，我們需要先指定要安裝的 CRI-O 版本及 OS，這邊因為預計安裝的 CRI-O 版本為 `1.24` ，以及在 Infra Lab 建立的雲實例 OS 是 `Ubuntu 22.04`，因此根據[官方文件](https://github.com/cri-o/cri-o/blob/main/install-legacy.md#apt-based-operating-systems)透過指令設定如下:
```

2024-03-30 17:07 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +因為我們在 OpenStack 上是以 Ubuntu 作為作業系統，在官方文件上有[對應的安裝方式](https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems)。接下來的指令需要以 root 權限執行:
可以在這裡說明要安裝哪一個版本。

2024-03-30 17:07 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +:::
Ubuntu 22.04 是 based on Debian Bullseye，看一下說明似乎是不需要 buster-backports 或 libseccomp2？能否協助確認？

2024-04-13 17:14 UTC, tico88612 commented on docs/self-paced-labs/kubeadm/index.md
> +接著重新執行 `kebeadm join` 的指令並帶入新的 `token` 和 `sha256` 即可。
typo
```suggestion
接著重新執行 `kubeadm join` 的指令並帶入新的 `token` 和 `sha256` 即可。
```

2024-04-14 02:51 UTC, tico88612 approved these changes

2024-04-14 02:53 UTC, merged