Add Prometheus Exporter lab
cloud-native-taiwan/Infra-Labs-Docs pull request #67
Opened 2024-02-19 06:57 UTC by cdxvy30

This commit provides the tutorial of using Prometheus Operator to install Prometheus and Grafana, and then deploy the application (MongoDB) and its exporter sidecar container to expose metrics data to Prometheus. Finally, the data could be displayed on Grafana.

2024-02-25 09:06 UTC, ching-kuo reviewed
some comments

2024-02-25 09:06 UTC, ching-kuo commented on docs/self-paced-labs/prometheus/index.md
> +4. Pushgateway: 短於 Retrieval 拉取資料的工作週期的 metrics，則透過 Pushgateway 蒐集。
我印象中 pushgateway 是用在特殊情況不適合用 pull 的時候，畢竟 pull 的 interval 是可以調整的。
這邊你要不要確認一下？

2024-02-25 09:06 UTC, ching-kuo commented on docs/self-paced-labs/prometheus/index.md
> +## 在 OpenStack 上架設 Prometheus
由於是在 Kubernetes 上架設的，個人認為跟 OpenStack 沒什麼關係

建議：
`在 Kubernetes 上架設 Prometheus`

2024-02-25 09:06 UTC, ching-kuo commented on docs/self-paced-labs/prometheus/index.md
> +其中第 71 行的 `.spec.serviceMonitorSelector` 就是 Prometheus 選擇要註冊哪些 ServiceMonitor 的規則，目前的規則為空 ( `{}` )，代表任何 ServiceMonitor 都會被 Prometheus 給註冊用來抓取服務的 metrics data。
印象中網站 render 出來不會有行數，應該可以省略

2024-02-26 13:26 UTC, cdxvy30 commented on docs/self-paced-labs/prometheus/index.md
> +其中第 71 行的 `.spec.serviceMonitorSelector` 就是 Prometheus 選擇要註冊哪些 ServiceMonitor 的規則，目前的規則為空 ( `{}` )，代表任何 ServiceMonitor 都會被 Prometheus 給註冊用來抓取服務的 metrics data。
這邊我想說檔案內容較長，所以有去找 Docusaurus 的文件設定，是可以 render 行數並 highlight 該行，如果不妥我再拿掉。網頁 render 出來會像這樣:
<img width="842" alt="Screenshot 2024-02-26 at 9 26 20 PM" src="https://github.com/cloud-native-taiwan/Infra-Labs-Docs/assets/109569898/d6afb5b0-a840-408e-8915-5358e7c61ed2">

2024-02-26 13:52 UTC, cdxvy30 commented on docs/self-paced-labs/prometheus/index.md
> +4. Pushgateway: 短於 Retrieval 拉取資料的工作週期的 metrics，則透過 Pushgateway 蒐集。
的確我這樣敘述太過片面，如果改成「PushGateway: 由於 PushGateway 在監控多個實體時，可能成為單點故障或潛在瓶頸，且某種程度上也失去 Prometheus 自動監控各實體的設計，因此需相當注意使用時機；通常只用於不適用 pull 機制的場景，例如 service-level 的 batch job」這樣敘述呢？

2024-03-16 02:52 UTC, tico88612 requested changes
Initial review.

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +Prometheus 在過去幾年逐漸變成監控工具的代名詞，不僅能用在雲原生環境，也可用於傳統裸機部署環境。運用監控工具的優勢在於快速定位問題點，以往沒有監控概念的情況下，在現今漸趨複雜的微服務架構中，很難迅速找到錯誤的癥結點。而 Prometheus 正好可以解決這樣的痛點。
依照 [CNCF glossary 的繁體中文翻譯](https://glossary.cncf.io/zh-tw/)，應該為「雲端原生」
```suggestion
Prometheus 在過去幾年逐漸變成監控工具的代名詞，不僅能用在雲端原生環境，也可用於傳統裸機部署環境。運用監控工具的優勢在於快速定位問題點，以往沒有監控概念的情況下，在現今漸趨複雜的微服務架構中，很難迅速找到錯誤的癥結點。而 Prometheus 正好可以解決這樣的痛點。
```

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +```bash
純文字輸出不用 bash
```suggestion
```plain
```

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +```bash
純文字輸出不用 bash
```suggestion
```plain
```

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +```bash
純文字輸出不用 bash
```suggestion
```plain
```

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +要觀察這次安裝過程中，安裝了哪些資源，可透過 `kubectl get all -n prometheus-stack` 看到下列資訊:
這段敘述我會覺得有點龐統，因為安裝 `kube-prometheus-stack` 也包含其他內容（包含 CRD 等），我會建議改為下面這樣：

確認安裝的服務皆成功啟動（然後用 `kubectl -n prometheus-stack get pods -l "release=prometheus-stack"` 確認），跟上面的 NOTES 可以做對應

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +helm show values bitnami/mongodb > mongodb.yaml
需要指定版本

2024-03-16 02:52 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +helm install mongodb bitnami/mongodb -f mongodb.yaml
需要指定版本

2024-03-31 04:48 UTC, tico88612 reviewed
Second review.

2024-03-31 04:48 UTC, tico88612 commented on sidebars.js
>          'self-paced-labs/vault-secrets-store-csi-with-quarkus/index'
Add comma at the end.

2024-03-31 04:48 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +4. Pushgateway: PushGateway: 由於 PushGateway 在監控多個實體時，可能成為單點故障或潛在瓶頸，且某種程度上也失去 Prometheus 自動監控各實體的設計，因此需相當注意使用時機；通常只用於不適用 pull 機制的場景，例如 service-level 的 batch job。
看起來敘述是從這裡改的：https://prometheus.io/docs/practices/pushing/
建議先寫用途再寫限制。
可以想想看有沒有更好的舉例？service-level 的 batch job 有沒有使用場景？

```suggestion
4. Pushgateway: 通常只用於不適用 pull 機制的場景 (e.g. service-level 的 batch job)。由於 PushGateway 在監控多個實體時，可能成為單點故障或潛在瓶頸，且某種程度上也失去 Prometheus 自動監控各實體的設計，因此需相當注意使用時機。
```

2024-03-31 04:48 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +其中 `TYPE` 與 `HELP` 欄位作為註解用，提升可讀性，`Help` 主要是該段 metrics 的註解，而 `TYPE` 欄位會顯示該筆資料是什麼類型的 metrics。目前 Prometheus 提供 4 種類型的 metrics:
統一大小寫
```suggestion
其中 `TYPE` 與 `HELP` 欄位作為註解用，提升可讀性，`HELP` 主要是該段 metrics 的註解，而 `TYPE` 欄位會顯示該筆資料是什麼類型的 metrics。目前 Prometheus 提供 4 種類型的 metrics:
```

2024-03-31 04:48 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +:::****
這裡好像會把排版破壞掉

```suggestion
:::
```

<img width="845" alt="image" src="https://github.com/cloud-native-taiwan/Infra-Labs-Docs/assets/17496418/39a462fc-caa5-4ab9-913e-26383bc98baf">

2024-03-31 04:48 UTC, tico88612 commented on docs/self-paced-labs/prometheus/index.md
> +其中第 71 行的 `.spec.serviceMonitorSelector` 就是 Prometheus 選擇要註冊哪些 ServiceMonitor 的規則，目前的規則為空 ( `{}` )，代表任何 ServiceMonitor 都會被 Prometheus 給註冊用來抓取服務的 metrics data。
我認為這樣呈現沒問題

2024-04-03 10:40 UTC, tico88612 approved these changes
LGTM, thanks for your contribution!

2024-04-03 10:45 UTC, merged